# Generated by Django 2.2.1 on 2019-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('club', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
